### ISSUE TITLE
Вопросы по интерактивности

### ISSUE THREAD

**Issue by m3tro1d** [m3tro1d/entrepresenteur#43]
С прошлого раза:

- [x] ~~Реализовать невидимый input для инлайнового редактирования текста или названия презентации~~ #46 
- [x] Поработать над отображением текста в SlideView. Сейчас он выходит за границы элемента и странно отображается в левом верхнем углу
- [x] ~~Поработать над улучшением реализации undo/redo. В текущей есть сложности, и на redo падают ошибки~~ #47 

Актуальные:

- [x] mapStateToProps лучше вызывать в дочерних элементах, чтобы не пробрасывать его сверху по всей цепочке. Можно, например, в SlideThumbnail отправлять индекс слайда из списка
- [x] Поработать на фокусом списка слайдов и рабочей зоны (для реализации удаления на Delete). **Дополнительно**: подумать над навигацией табом
- [x] ~~Доработать useOnClickOutside, чтобы не деселектить остальные элементы при перемещении нескольких посредством drag and drop одного~~ #49 
- [x] Поразбираться, почему useDoubleClick не срабатывает, пока элемент не был заселекчен
- [x] Доработать useDragAndDrop, сделав его более абстрактным. Можно передавать в него хэндлеры onStart, onMove и onFinish, а позицию и дельту со скейлом считать уже в специализированном хуке для элементов, например, useSlideElementDragAndDrop. Либо возвращать фактическую дельту
- [x] ~~В связи с изменением механики drag and drop, возможно стоит вынести его в корневой компонент, и оттуда передавать дельту в элементы. Как один из способов реализовать перемещение нескольких элементов~~ #48 
- [x] Также вынести навешивание хоткеев
- [x] Подумать над разделением reducer'ов, конкретно над получением root state в обработчиках, например, слайдов (нужно знать selectedSlideIDs)
- [x] Поработать над ошибкой скрытого input `<input> picker was blocked due to lack of user activation`. ~~Можно использовать input с `display: none`, навешивать на него ref и уже его использовать для открытия презентации/картинок~~ Этот способ не работает :(
- [x] С текущей реализацией не получится оптимизировать useDragAndDrop, чтобы все время не вызывать dispatch и не триггерить обновление модели. Надо разделить представление слайда в превьюшке и в редактируемой зоне (например, SlideThumbnail и EditableSlide). Для отображения промежуточных состояний во время перетаскивания можно использовать `transform`, чтобы не триггерить полный цикл перерисовки DOM (поизучать)

**Comment by m3tro1d** [comment]
Выделил оставшееся в отдельные задачи
